const API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT
const WEB_URL = process.env.NEXT_PUBLIC_WEB_URL
const MEDIA_URL = process.env.NEXT_PUBLIC_MEDIA_ENDPOINT
const FIREBASE = {
  API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
}

export {
  API_ENDPOINT,
  WEB_URL,
  MEDIA_URL,
  FIREBASE
}